### PR TITLE
add zh_CN language file

### PR DESCRIPTION
**Pull request by jshengst**
I made this Chinese translation based on English and Russian.

### CODE REVIEW

**Comment by jshengst** [comment]
However, during testing, no matter which language I choose (including the existing French, Russian, etc.), I cannot switch to the corresponding language. 
Is it because the localization function is not yet completed? Or do I need to save and restart blender?

**Comment by xavier150** [comment]
Thanks you very much and sorry for the delay. <3
I will do test and tell you.

**Comment by xavier150** [comment]
Hum I think it the language code. It work for en_US, fr_FR, ru_RU, but not for zh_CN.

Using:
```
for t in bpy.app.translations.locales:
	print(t)
```

You can found: **zh_HANS** (Simplified Chinese) and **zh_HANT** (Traditional Chinese)

**Comment by xavier150** [comment]
Hello @jshengst !
I will update the language code name. Do you want me to use zh_HANS (Simplified Chinese) or zh_HANT (Traditional Chinese)?

**Comment by jshengst** [comment]
> Hello @jshengst ! 你好 ！ I will update the language code name. Do you want me to use zh_HANS (Simplified Chinese) or zh_HANT (Traditional Chinese)?我将更新语言代码名称。您希望我使用 zh_HANS（简体中文）还是 zh_HANT（繁体中文）？

Thanks, this is zh_HANS (Simplified Chinese)

**Comment by xavier150** [comment]
Thank you!!
image

I updated the dev branch. 
At the moment, not all terms are translatable because I have to add them manually in the source code but it is planned.

**Pull request merged**
